import printList from "../printList.js";

const vocab = {
  Dresseur: ["Entraîneur d’animaux", "nm"],
  Battrai: ["(je) vaincrai", "v"],
  Répit: ["Pause, repos", "nm"],
  Ferai: ["(j’) accomplirai", "v"],
  Vainqueur: ["Gagnant", "adj"],
  Défis: ["Épreuves", "nm"],
  Parcourrai: ["(je) traverserai", "v"],
  Mystères: ["Énigmes", "nm"],
  Victoire: ["Succès", "nf"],
  Arrêtera: ["Cessera", "v"],
  Triomphera: ["Gagnera", "v"],
  Âge: ["Nombre d’années vécues", "nm"],
  Courage: ["Bravoure", "nm"],
  Coup: ["Frappe, choc", "nm"],
  Riposte: ["Réponse, contre-attaque", "nf"],
  Hypnotique: ["Qui provoque le sommeil", "adj"],
  Serait: ["Deviendrait", "v"],
  Vient: ["A tout juste (______ de)", "v"],
  Rappeler: ["Faire revenir", "v"],
  Géant: ["Très grand", "adj"],
  Garçon: ["Jeune homme", "nm"],
  Bourg: ["Petit village", "nm"],
  Brevet: ["Diplôme, certificat", "nm"],
  Débutant: ["Apprenti, novice", "nm"],
  Chêne: ["Arbre très solide", "nm"],
  Voyagerai: ["Ferai un trajet", "v"],
  Dresseurs: ["Entraîneurs d’animaux", "nm"],
  Serments: ["Promesses solennelles", "nm"],
  Suffit: ["(C') est assez", "v"],
  Devrais: ["Obligation possible", "v"],
  Pars: ["Je quitte, je m'en vais", "v"],
  Dormir: ["Se reposer la nuit", "v"],
  Nerveux: ["Anxieux, agité", "adj"],
  Vais: ["Verbe qui implique le futur (je _______)", "v"],
  Bulbizarre: ["Pokémon plante", "nm"],
  Salamèche: ["Pokémon feu", "nm"],
  Carapuce: ["Pokémon eau", "nm"],
  Choisirez: ["Sélectionnerez", "v"],
  Promets: ["(Je) garantis; (J') assure", "v"],
  Pyjama: ["Vêtement de nuit", "nm"],
  Gagner: ["Remporter, obtenir la victoire", "v"],
  Spécialistes: ["Experts, connaisseurs", "nm/nf"],
  Laissez: ["Permettez", "v"],
  Tard: ["Après l'heure prévue", "adv"],
  Jamais: ["À aucun moment", "adv"],
  Rencontrer: ["Faire connaissance", "v"],
  Encouragements: ["Paroles de soutien", "nf"],
  Soit: ["Pour qu'il _______ (verbe être)", "v"],
  Entier: ["Complet, total", "adj"],
  Arrivé: ["Venu, atteint un lieu", "v"],
  Aurais: ["Tu aurais vu (conditionnel passé) (AUX)", "v"],
  Assister: ["Être présent", "v"],
  Coucher: ["Aller dormir", "v"],
  Tenue: ["Vêtement, habit", "nf"],
  Réfléchi: ["(J'ai) contemplé", "v"],
  "Tant-pis": ["C'est dommage, c'est regrettable", "interj"],
  Servi: ["Aidé, fourni", "v"],
  Veuilles: ["Souhaites (au subjonctif)", "v"],
  Prévenir: ["Avertir, alerter", "v"],
};

printList(vocab, "vocab-table");